development:
      host: localhost
      adapter: mysql2
      database: traveller_development
      port: 3306
      username: root
      password: t

test: &test
      host: localhost
      adapter: mysql2
      database: traveller_test
      port: 3306
      username: root
      password: t

production:
      host: localhost
      adapter: mysql2
      database: traveller_production
      port: 3306
      username: root
      password: t
cucumber:
  <<: *test